version: '3.2'

services:
  dwra_db:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
      - ${DB_INIT_PATH}:/docker-entrypoint-initdb.d:ro
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: dwrra_db
      MYSQL_ROOT_PASSWORD: cpic!1011
    command: --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    logging:
      options:
        max-size: 10mb

  dwra_redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONF_PATH}:/usr/local/etc/redis
    environment:
      TZ: Asia/Shanghai
    command: /usr/local/etc/redis/redis.conf
    logging:
      options:
        max-size: 10mb
        
